name: shadhinota_canvas_2026
description: "A photocard generator to resemble the voice of protesters in Bangladesh"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  flex_color_picker: ^3.6.0
  image_gallery_saver_plus: ^4.0.1
  url_launcher: ^6.3.2
  icons_plus: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "FFFFFF"
  color_dark: "1E1E1E"
  image: assets/sc.png
  fullscreen: true
  android_12:
    color: "FFFFFF"
    color_dark: "1E1E1E"
    image: assets/sc.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  assets:
    - bg/
    - assets/

  fonts:
    - family: Hadi
      fonts:
        - asset: fonts/Hadi.ttf
    - family: HadiRounded
      fonts:
        - asset: fonts/Hadi (Rounded).ttf
    - family: AbuSayed
      fonts:
        - asset: fonts/abu_sayed.ttf

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/sc.png"
  min_sdk_android: 21